language: c
sudo: false
cache: directories:
  - ~/arduino_ide
  - ~/.arduino15/packages/
git:
  depth: false
  quiet: false
env:
  global:

before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
install:

script:
  - build_main_platforms
notifications:
  email:
    on_success: change
    on_failure: change

